"""Add photo path string

Revision ID: 58f9fad46783
Revises: e4cc726ba51a
Create Date: 2024-12-13 23:54:57.008679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f9fad46783'
down_revision: Union[str, None] = 'e4cc726ba51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('photo', sa.String(length=255), nullable=True))
    op.add_column('managers', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'photo')
    op.drop_column('admins', 'photo')
    # ### end Alembic commands ###
