"""Add skils, notes and favorites

Revision ID: 87f90cb7e67e
Revises: d834e2c06fd2
Create Date: 2024-12-05 17:14:16.556235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87f90cb7e67e"
down_revision: Union[str, None] = "d834e2c06fd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidate_skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=True),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_skills_candidate_id"),
        "candidate_skills",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_skills_skill_id"),
        "candidate_skills",
        ["skill_id"],
        unique=False,
    )
    op.add_column(
        "manager_candidates", sa.Column("is_favorite", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "manager_candidates", sa.Column("note", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_manager_candidates_is_favorite"),
        "manager_candidates",
        ["is_favorite"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_manager_candidates_is_favorite"), table_name="manager_candidates"
    )
    op.drop_column("manager_candidates", "note")
    op.drop_column("manager_candidates", "is_favorite")
    op.drop_index(op.f("ix_candidate_skills_skill_id"), table_name="candidate_skills")
    op.drop_index(
        op.f("ix_candidate_skills_candidate_id"), table_name="candidate_skills"
    )
    op.drop_table("candidate_skills")
    op.drop_table("skills")
    # ### end Alembic commands ###
