"""Rename course to course_id

Revision ID: a657c709ec06
Revises: 429d71b7d7b8
Create Date: 2024-11-28 22:17:30.746541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a657c709ec06'
down_revision: Union[str, None] = '429d71b7d7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_courses', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_candidate_courses_course_id'), 'candidate_courses', ['course_id'], unique=False)
    op.create_foreign_key(None, 'candidate_courses', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_courses', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_courses_course_id'), table_name='candidate_courses')
    op.drop_column('candidate_courses', 'course_id')
    # ### end Alembic commands ###
