"""Initial commit

Revision ID: daef1d8dc085
Revises: 
Create Date: 2024-12-13 19:13:44.403933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daef1d8dc085'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'date_of_birth')
    op.drop_column('candidates', 'years_of_experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
