"""Add date_of_birth and years_of_expirience for candidate

Revision ID: dd0f367a529d
Revises: a58729e93e85
Create Date: 2024-12-12 21:35:22.257724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0f367a529d'
down_revision: Union[str, None] = 'a58729e93e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'years_of_experience')
    op.drop_column('candidates', 'date_of_birth')
    # ### end Alembic commands ###
